<?php

/**
 * @file
 * PHP file {ercore_other_product.module} for use with eightball.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * Form Alter for ERCore Other Product nodes.
 */
function ercore_other_product_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_ercore_other_product_form' || $form_id === 'node_ercore_other_product_edit_form') {
    // Makes Website field visible if type value  is set to 7 (website).
    $form['field_ercore_op_website']['#states'] = array(
      'visible' => array(
        ':input[name="field_ercore_op_type"]' => array('value' => 7),
      ),
    );
  }
}
