<?php

/**
 * @file
 * Hook implementations for the ERCore module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_alter().
 */
function ercore_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Set current user to default valuie of organizer field.
  $forms = [
    'node_ercore_collaboration_form',
    'node_ercore_event_form',
    'node_ercore_j_highlight_form',
    'node_ercore_other_product_form',
    'node_ercore_j_honor_form',
    'node_ercore_patent_form',
    'node_ercore_presentation_form',
    'node_ercore_proposal_form',
    'node_ercore_publication_form',
  ];
  if (in_array($form_id, $forms)) {
    $current_user = \Drupal::currentUser();
    $user = User::load($current_user->id());
    $form['field_ercore_organizer']['widget'][0]['target_id']['#default_value'] = $user;
  }
  // User form logic.
  if ($form_id === 'user_form') {
    // Post Doc.
    $form['field_ercore_user_mentor_plan']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'post-doc'],
      ],
    ];
    $form['field_ercore_user_mentor_plan_dt']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'post-doc'],
      ],
    ];

    // Graduate.
    $form['field_ercore_user_master_act']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'graduate'],
      ],
    ];
    $form['field_ercore_user_master_ant']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'graduate'],
      ],
    ];
    $form['field_ercore_user_doc_act']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'graduate'],
      ],
    ];
    $form['field_ercore_user_doc_ant']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'graduate'],
      ],
    ];
    // Undergraduate.
    $form['field_ercore_user_under_act']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'undergraduate'],
      ],
    ];
    $form['field_ercore_user_under_ant']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'undergraduate'],
      ],
    ];

    // Advisor & Mentor.
    $form['field_ercore_user_advisor_mentor']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => [
          ['value' => 'post-doc'],
          ['value' => 'graduate'],
        ],
      ],
    ];

    // Faculty / Non-Technical.
    // Boards and Committees.
    $form['field_ercore_user_boards']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => [
          ['value' => 'faculty'],
          ['value' => 'non-technical'],
        ],
      ],
    ];

    // Management team.
    $form['field_ercore_user_lead_team']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => [
          ['value' => 'faculty'],
          ['value' => 'non-technical'],
        ],
      ],
      'required' => [
        ':input[name="field_ercore_senior_role"]' => [
          ['value' => 'faculty'],
          ['value' => 'non-technical'],
        ],
      ],
    ];
    // Demographics.
    $form['field_ercore_user_gender']['#states'] = [
      'disabled' => [
        ':input[name="field_ercore_prefer_no_answer[value]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_ercore_user_ethnicity']['#states'] = [
      'disabled' => [
        ':input[name="field_ercore_prefer_no_answer[value]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_ercore_user_race']['#states'] = [
      'disabled' => [
        ':input[name="field_ercore_prefer_no_answer[value]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_ercore_user_disabilities']['#states'] = [
      'disabled' => [
        ':input[name="field_ercore_prefer_no_answer[value]"]' => ['checked' => TRUE],
      ],
    ];
    // RCR.
    $form['field_ercore_user_rcr_status']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => [
          ['value' => 'undergraduate'],
          ['value' => 'graduate'],
        ],
      ],
    ];
    $form['field_ercore_user_rcr_per']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_rcr_status"]' => ['value' => 1],
      ],
    ];
    $form['field_ercore_user_rcr_per_up']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_rcr_status"]' => ['value' => 1],
      ],
    ];
    $form['field_ercore_user_rcr_on']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_rcr_status"]' => ['value' => 1],
      ],
    ];
    $form['field_ercore_user_rcr_on_up']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_rcr_status"]' => ['value' => 1],
      ],
    ];

    // Salary support.
    // Remove n/a option from field_ercore_us_fac_support.
    unset($form['field_ercore_user_fac_support']['widget']['#options']['_none']);

    // Faculty.
    $form['field_ercore_user_fac_support']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'faculty'],
      ],
      'required' => [
        ':input[name="field_ercore_senior_role"]' => ['value' => 'faculty'],
      ],
    ];

    // Data collection.
    $form['field_ercore_user_data_desc']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_collecting[value]"]' => ['checked' => TRUE],
      ],
      'required' => [
        ':input[name="field_ercore_user_collecting[value]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_ercore_user_data_ongoing']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_collecting[value]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_ercore_user_data_date']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_collecting[value]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_ercore_user_data_mgr']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_collecting[value]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_ercore_user_data_url']['#states'] = [
      'visible' => [
        ':input[name="field_ercore_user_collecting[value]"]' => ['checked' => TRUE],
      ],
    ];
    // Primary email.
    $mail = $form['account']['mail']['#default_value'];
    $primary = '<div class="form-wrapper"><div class="form-item"><div class="label">Primary Email</div> ' . $mail . '</div><div class="description">Primary Drupal email, editable on Account Information tab.</div></div>';
    $form['field_ercore_user_second_email']['#prefix'] = $primary;
    $form['#validate'][] = 'ercore_core_form_validate';
  }
}

/**
 * Validates submission values in the FORM_ID() form.
 */
function ercore_core_form_validate(array &$form, FormStateInterface $form_state) {
  $value1 = $form_state->getValue('field_ercore_user_start');
  $value2 = $form_state->getValue('field_ercore_user_end');
  if (!empty($value2['0']['value']) && $value2['0']['value'] < $value1['0']['value']) {
    $form_state->setErrorByName('field_ercore_user_end', t('End date must be after start date.'));
  }
}
