<?php

/**
 * @file
 * PHP file {ercore_patent.module} for use with eightball.
 */

/**
 * Implements hook_form_alter().
 */
function ercore_patent_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_ercore_patent_form' || $form_id === 'node_ercore_patent_edit_form') {
    ksm($form['field_ercore_pt_license']['widget']['0']['value']['#states'], 'before');
    $form['field_ercore_pt_license']['#states'] = array(
      'visible' => array(
        ':input[name="field_ercore_pt_licensed[value]"]' => array('checked' => TRUE),
      ),
    );
    $form['field_ercore_pt_license']['widget']['0']['value']['#states'] = array(
      'required' => array(
        ':input[name="field_ercore_pt_licensed[value]"]' => array('checked' => TRUE),
      ),
    );
    $form['field_ercore_pt_licensee']['#states'] = array(
      'visible' => array(
        ':input[name="field_ercore_pt_licensed[value]"]' => array('checked' => TRUE),
      ),
    );
    $form['field_ercore_pt_licensee']['widget']['0']['target_id']['#states'] = array(
      'required' => array(
        ':input[name="field_ercore_pt_licensed[value]"]' => array('checked' => TRUE),
      ),
    );
    ksm($form['field_ercore_pt_license']['widget']['0']['value']['#states'], 'after');
  }
}
